<?php
/*
 * Implementation of hook_block_view().
 */
function jwd_%machine_name%_workflow_block_view_alter(&$data, $block)
{
  switch($block->delta) {
    case 'jwd_workflow_products':
      $data['content'] = str_replace('<h4>Bestandskunden</h4>',
        "<h4>%name%</h4>
        <ul>
          <li>" . l("neues %name%-Produkt","admin/commerce/products/add/jwd-%machine_name%-product",array("query"=>drupal_get_destination())) . "</li>
          <li>" . l("neue %name%-Produktansicht","node/add/jwd-%machine_name%-product-display",array("query"=>drupal_get_destination())) . "</li>
          <li>" . l("%name% Produktkategorien bearbeiten","admin/structure/taxonomy/produktkategorien_%machine_name%") . "</li>
        </ul>
        <h4>Bestandskunden</h4>",
        $data['content']
      );
      break;
    case 'jwd_workflow_various':
      $data['content'] = str_replace('</ul>', "<li>" . l("%name% Menü bearbeiten","admin/structure/menu/manage/menu-%machine_name%") . "</li></ul>", $data['content']);
      break;
  }
}