<?php
/**
 * @file
 * Code for the JWD %name% Search feature.
 */

function jwd_%machine_name%_search_enable()
{
  $value = variable_get('search_config', array());
  if (!in_array(%role_id%, $value['fields']['containing_any']['roles'])) $value['fields']['containing_any']['roles'][] = 0;
  if (!in_array(%role_id%, $value['fields']['containing_phrase']['roles'])) $value['fields']['containing_phrase']['roles'][] = 0;
  if (!in_array(%role_id%, $value['fields']['containing_none']['roles'])) $value['fields']['containing_none']['roles'][] = 0;
  if (!in_array(%role_id%, $value['fields']['types']['roles'])) $value['fields']['types']['roles'][] = 0;
  if (!in_array(%role_id%, $value['fields']['category']['roles'])) $value['fields']['category']['roles'][] = 0;
  variable_set('search_config', $value);
}