<?php

function jwd_bmw_menus_enable() {
  $exists = db_query("SELECT COUNT(*) FROM {block_role} WHERE module='menu_block' AND delta='jwd_bmw_menus-main' AND rid='52'")->fetchAssoc();
  $exists = intval($exists['COUNT(*)']);

  if (!$exists) {
    db_insert('block_role')
      ->fields(array(
        'module' => 'menu_block',
        'delta' => 'jwd_bmw_menus-main',
        'rid' => '52',
      ))
      ->execute();
  }

  $exists = db_query("SELECT COUNT(*) FROM {block} WHERE module='menu_block' AND delta='jwd_bmw_menus-main' AND theme='jwd_frontend'")->fetchAssoc();
  $exists = intval($exists['COUNT(*)']);

  if (!$exists) {
    db_insert('block')
      ->fields(array(
        'module' => 'menu_block',
        'delta' => 'jwd_bmw_menus-main',
        'theme' => 'jwd_frontend',
        'status' => '1',
        'weight'=> '0',
        'region' => 'navigation',
        'custom' => '0',
        'visibility' => '0',
        'pages' => '',
        'cache' => '-1',
        'title' => ''
      ))
      ->execute();
  }
}

/**
 * Implements hook_menu_block_blocks().
 */
function jwd_bmw_menus_menu_block_blocks() {
    // The array key is the block delta used by menu block.
    return array(
        'jwd_bmw_menus-main' => array(
            'menu_name'   => 'menu-bmw',
            'parent_mlid' => 0,
            'title_link'  => 0,
            'admin_title' => 'BMW (Dropdown)',
            'level'       => 1,
            'follow'      => 0,
            'depth'       => 3,
            'expanded'    => 1,
            'sort'        => 0,
            'status'      => 1
        ),
        'jwd_bmw_menus-cat_tabs' => array(
            'menu_name'   => 'menu-bmw',
            'parent_mlid' => 28281,
            'title_link'  => 0,
            'admin_title' => t('Category tabs BMW'),
            'level'       => 1,
            'follow'      => 0,
            'depth'       => 2,
            'expanded'    => 1,
            'sort'        => 0,
        ),
    );
}