<?php
/*
 * Implementation of hook_wysiwyg_editor_settings_alter().
 */
function markitup_extras_wysiwyg_editor_settings_alter(&$settings,&$context)
{
    //dsm($settings);
    //dsm($context);
    if ($context['profile']->editor == 'markitup') {
        $settings['markupSet']['h1'] = array(
            'name' => t('Heading 1'),
            'className' => 'markitup-h1',
            'key' => '1',
            'openWith' => '<h1(!( class="[![Class]!]")!)>',
            'closeWith' => '</h1>',
            'placeHolder' => 'Your title here...',
     	);
        $settings['markupSet']['h2'] = array(
            'name' => t('Heading 2'),
            'className' => 'markitup-h2',
            'key' => '2',
            'openWith' => '<h2(!( class="[![Class]!]")!)>',
            'closeWith' => '</h2>',
            'placeHolder' => 'Your title here...',
        );
        $settings['markupSet']['h3'] = array(
            'name' => t('Heading 3'),
            'className' => 'markitup-h3',
            'key' => '3',
            'openWith' => '<h3(!( class="[![Class]!]")!)>',
            'closeWith' => '</h3>',
            'placeHolder' => 'Your title here...',
        );
        $settings['markupSet']['h4'] = array(
            'name' => t('Heading 4'),
            'className' => 'markitup-h4',
            'key' => '4',
            'openWith' => '<h4(!( class="[![Class]!]")!)>',
            'closeWith' => '</h4>',
            'placeHolder' => 'Your title here...',
        );
        $settings['markupSet']['paragraph'] = array(
            'name' => t('Paragraph'),
            'className' => 'markitup-paragraph',
            'key' => 'p',
            'openWith' => '<p(!( class="[![Class]!]")!)>',
            'closeWith' => '</p>',
        );
    }
}