<?php
/**
 * @file
 * Code for the JWD %name% Registration.
 */

function jwd_%machine_name%_registration_enable()
{
  $value = variable_get('autoassignrole_user_roles', array());
  $value[%role_id%] = '%role_id%';
  variable_set('autoassignrole_user_roles', $value);

  $value = variable_get('jwd_product_bestandskunden_roles', array());
  if (!in_array(%role_id%, $value)) {
    $value[] = %role_id%;
  }
  variable_set('autoassignrole_user_roles', $value);

  $value = variable_get('jwd_user_registration_authorized_roles', array());
  if (!in_array(%role_id%, $value)) {
    $value[] = %role_id%;
  }
  variable_set('jwd_user_registration_authorized_roles', $value);
}